{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ include "awx.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: web
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.awx_web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "awx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "awx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.awx_web.image.repository }}:{{ .Values.awx_web.image.tag }}"
          imagePullPolicy: {{ .Values.awx_web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - mountPath: /etc/tower
              name: {{ include "awx.fullname" . }}-application-config
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: {{ include "awx.fullname" . }}-application-config-nginx
            - name: {{ include "awx.fullname" . }}-application-credentials
              mountPath: "/etc/tower/conf.d/"
              readOnly: true
          env:
            - name: DATABASE_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DATABASE_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: DATABASE_HOST
              value: {{ .Values.postgresql.postgresqlHost }}
            - name: DATABASE_PORT
              value: {{ .Values.postgresql.postgresqlPort | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: MEMCACHED_HOST
              value: {{ include "awx.fullname" . }}-memcached
            - name: RABBITMQ_HOST
              value: {{ include "awx.fullname" . }}-rabbitmq
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "awx.fullname" . }}-application-config
          configMap:
            name: {{ include "awx.fullname" . }}-application-config
            items:
              - key: awx_settings
                path: settings.py
              - key: secret_key
                path: SECRET_KEY
        - name: {{ include "awx.fullname" . }}-application-config-nginx
          configMap:
            name: {{ include "awx.fullname" . }}-application-config
            items:
              - key: nginx_conf
                path: nginx.conf
        - name: "{{ include "awx.fullname" . }}-application-credentials"
          configMap:
            name: {{ include "awx.fullname" . }}-application-config
            items:
              - key: environment_sh
                path: 'environment.sh'
